"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from "react";
import type { FocusSession, TimerMode, TimerPreferences, TimerSnapshot } from "@/lib/types";
import { nextBreakMode, remainingSeconds } from "@/lib/timer";
import { useToast } from "@/components/ToastProvider";

type Action="pause"|"resume"|"complete"|"skip"|"cancel";
type TimerContextValue=TimerSnapshot&{loading:boolean;pending:boolean;offline:boolean;error:string|null;remaining:number;reload:()=>Promise<void>;start:(mode:TimerMode,taskId?:string|null)=>Promise<void>;act:(action:Action)=>Promise<void>;savePreferences:(value:TimerPreferences)=>Promise<void>;enableBrowserNotifications:()=>Promise<void>;markRead:(id?:string)=>Promise<void>};
const defaults:TimerSnapshot={session:null,preferences:{focusMinutes:50,shortBreakMinutes:10,longBreakMinutes:30,longBreakAfterSessions:4,autoStartBreak:false,autoStartFocus:false,soundEnabled:true,browserNotificationsEnabled:false,breakAlertsEnabled:true,inAppAlertsEnabled:true},notifications:[],completedFocusToday:0,focusSecondsToday:0};
const Context=createContext<TimerContextValue|null>(null);
async function request(url:string,options?:RequestInit){const response=await fetch(url,{cache:"no-store",...options});const body=await response.json();if(!response.ok)throw new Error(body.error??"Timer request failed.");return body;}
function playAlert(){try{const AudioContextClass=window.AudioContext||(window as typeof window&{webkitAudioContext:typeof AudioContext}).webkitAudioContext;const context=new AudioContextClass();const oscillator=context.createOscillator();const gain=context.createGain();oscillator.frequency.value=740;gain.gain.setValueAtTime(.12,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.55);oscillator.connect(gain);gain.connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.55);}catch(error){console.warn("Sound alert unavailable.",error);}}
export function TimerProvider({children}:{children:React.ReactNode}){
 const {showToast}=useToast();
 const [snapshot,setSnapshot]=useState(defaults);const [loading,setLoading]=useState(true);const [pending,setPending]=useState(false);const [offline,setOffline]=useState(false);const [error,setError]=useState<string|null>(null);const [remaining,setRemaining]=useState(0);const channel=useRef<BroadcastChannel|null>(null);const finishing=useRef(false);
 const reload=useCallback(async()=>{try{const data=await request("/api/timer");setSnapshot(data);setError(null);}catch(cause){setError(cause instanceof Error?cause.message:"Timer could not sync.");}finally{setLoading(false);}},[]);
 useEffect(()=>{const handle=window.setTimeout(()=>{setOffline(!navigator.onLine);void reload()},0);const online=()=>{setOffline(false);void reload();};const offlineHandler=()=>setOffline(true);window.addEventListener("online",online);window.addEventListener("offline",offlineHandler);if("BroadcastChannel"in window){channel.current=new BroadcastChannel("grand-blue-timer");channel.current.onmessage=()=>void reload();}return()=>{clearTimeout(handle);window.removeEventListener("online",online);window.removeEventListener("offline",offlineHandler);channel.current?.close();};},[reload]);
 useEffect(()=>{const tick=()=>setRemaining(remainingSeconds(snapshot.session));tick();const interval=window.setInterval(tick,1000);return()=>clearInterval(interval);},[snapshot.session]);
 const notify=useCallback((session:FocusSession)=>{const key=`grand-blue.alert.${session.id}`;if(localStorage.getItem(key))return;localStorage.setItem(key,"1");if(snapshot.preferences.soundEnabled)playAlert();if(snapshot.preferences.browserNotificationsEnabled&&"Notification"in window&&Notification.permission==="granted")new Notification(session.mode==="focus"?"Focus session complete":"Break complete",{body:"Your Grand Blue timer reached zero.",tag:session.id});},[snapshot.preferences]);
 const run=useCallback(async(url:string,body:unknown)=>{if(pending||offline)throw new Error(offline?"Reconnect before changing the timer.":"A timer update is already pending.");setPending(true);try{const data=await request(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});channel.current?.postMessage("changed");return data;}catch(cause){const message=cause instanceof Error?cause.message:"Timer update failed.";setError(message);showToast("Update failed",message,"error");throw cause;}finally{setPending(false);}},[pending,offline,showToast]);
 const start=useCallback(async(mode:TimerMode,taskId?:string|null)=>{const minutes=mode==="focus"?snapshot.preferences.focusMinutes:mode==="short_break"?snapshot.preferences.shortBreakMinutes:snapshot.preferences.longBreakMinutes;const data=await run("/api/timer/start",{mode,durationSeconds:minutes*60,taskId:taskId??null,requestId:crypto.randomUUID()});setSnapshot((old)=>({...old,session:data.session}));setError(null);showToast(mode==="focus"?"Focus session started":"Break started",`${minutes} minute timer is running.`);},[run,snapshot.preferences,showToast]);
 const act=useCallback(async(action:Action)=>{const current=snapshot.session;if(!current)return;const data=await run("/api/timer/mutate",{sessionId:current.id,expectedVersion:current.version,action});const terminal=["complete","skip","cancel"].includes(action);if(action==="complete")notify(data.session);setSnapshot((old)=>({...old,session:terminal?null:data.session,completedFocusToday:old.completedFocusToday+(action==="complete"&&current.mode==="focus"?1:0),focusSecondsToday:old.focusSecondsToday+(action==="complete"&&current.mode==="focus"?data.session.actualFocusSeconds:0)}));showToast(action==="pause"?"Timer paused":action==="resume"?"Timer resumed":action==="complete"?"Session completed":action==="skip"?"Session skipped":"Timer reset");if(action==="complete"){const autoMode=current.mode==="focus"&&snapshot.preferences.autoStartBreak?nextBreakMode(snapshot.completedFocusToday+1,snapshot.preferences.longBreakAfterSessions):current.mode!=="focus"&&snapshot.preferences.autoStartFocus?"focus":null;if(autoMode)await start(autoMode);}void reload();},[snapshot,run,notify,start,reload,showToast]);
 useEffect(()=>{if(snapshot.session?.status==="active"&&remaining===0&&!finishing.current){finishing.current=true;void act("complete").finally(()=>{finishing.current=false;});}},[remaining,snapshot.session,act]);
 const savePreferences=useCallback(async(value:TimerPreferences)=>{setPending(true);try{await request("/api/timer/preferences",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(value)});setSnapshot((old)=>({...old,preferences:value}));channel.current?.postMessage("changed");setError(null);showToast("Settings saved","Timer and notification preferences are up to date.");}catch(cause){const message=cause instanceof Error?cause.message:"Preferences could not be saved.";setError(message);showToast("Save failed",message,"error");throw cause;}finally{setPending(false);}},[showToast]);
 const enableBrowserNotifications=useCallback(async()=>{if(!("Notification"in window))throw new Error("Browser notifications are not supported here.");const permission=await Notification.requestPermission();if(permission!=="granted")throw new Error("Browser notification permission was not granted.");await savePreferences({...snapshot.preferences,browserNotificationsEnabled:true});},[savePreferences,snapshot.preferences]);
 const markRead=useCallback(async(id?:string)=>{await request("/api/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(id?{id}:{all:true})});await reload();showToast(id?"Notification read":"Notifications cleared");},[reload,showToast]);
 const value=useMemo(()=>({...snapshot,loading,pending,offline,error,remaining,reload,start,act,savePreferences,enableBrowserNotifications,markRead}),[snapshot,loading,pending,offline,error,remaining,reload,start,act,savePreferences,enableBrowserNotifications,markRead]);return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useTimer(){const value=useContext(Context);if(!value)throw new Error("useTimer must be used within TimerProvider.");return value;}
