"use client";
import { FormEvent, useMemo, useState } from "react";
import { useLearning } from "@/components/LearningProvider";
import type { LearningTask, PlanWeek, TaskCategory, TaskPriority } from "@/lib/types";
import { dateKeyInTimeZone } from "@/lib/metrics";
import styles from "./page.module.css";

type Filter = "all" | "today" | "upcoming" | "completed";

export default function PlanPage() {
  const { plan, profile, loading, error, createTask, updateTask, deleteTask, reorderTasks, updateWeek } = useLearning();
  const today = dateKeyInTimeZone(new Date(), profile?.timezone ?? "UTC");
  const [filter, setFilter] = useState<Filter>("all"); const [openWeek, setOpenWeek] = useState<string | null>(null); const [editingTask, setEditingTask] = useState<LearningTask | null>(null); const [editingWeek, setEditingWeek] = useState<PlanWeek | null>(null); const [busy, setBusy] = useState(false);
  const allTasks = useMemo(() => plan?.weeks.flatMap((week) => week.tasks) ?? [], [plan]);
  const visible = (task: LearningTask) => filter === "all" || (filter === "completed" ? Boolean(task.completedAt) : filter === "today" ? !task.completedAt && task.scheduledDate === today : !task.completedAt && Boolean(task.scheduledDate && task.scheduledDate > today));
  if (loading) return <div className={styles.state}>Loading your six-week plan…</div>;
  if (error) return <div className="error-banner" role="alert">{error}</div>;
  if (!plan) return <div className={styles.state}>Your plan could not be prepared.</div>;
  const completed = allTasks.filter((task) => task.completedAt).length; const progress = allTasks.length ? Math.round(completed / allTasks.length * 100) : 0;

  return <div className={styles.page}><header className={styles.heading}><div><span className="eyebrow">Six-week system</span><h1>{plan.title}</h1><p>{plan.description}</p></div><div className={styles.overall}><strong>{progress}%</strong><span>{completed}/{allTasks.length} tasks complete</span></div></header>
    <div className={styles.filters}>{(["all","today","upcoming","completed"] as Filter[]).map((item) => <button key={item} className={filter === item ? styles.active : ""} onClick={() => setFilter(item)}>{item}</button>)}</div>
    <div className={styles.weeks}>{plan.weeks.map((week) => { const weekTasks = week.tasks.filter(visible); const weekDone = week.tasks.filter((task) => task.completedAt).length; const percent = week.tasks.length ? Math.round(weekDone / week.tasks.length * 100) : 0; return <section className={styles.week} key={week.id}><header><span className={styles.number}>W{week.weekNumber}</span><div><h2>{week.title}</h2><p>{week.description || week.outcome}</p><small>{week.startsOn ?? "Unscheduled"} → {week.endsOn ?? "Unscheduled"} · {(week.targetMinutes / 60).toFixed(0)}h target</small></div><div className={styles.weekProgress}><strong>{percent}%</strong><button onClick={() => setEditingWeek(week)}>Edit week</button></div></header>
      <div className={styles.taskList}>{weekTasks.length ? weekTasks.map((task, index) => <article key={task.id} className={`${styles.task} ${task.completedAt ? styles.done : ""}`}><button className={styles.check} aria-label={task.completedAt ? `Mark ${task.title} incomplete` : `Complete ${task.title}`} disabled={busy} onClick={async () => { setBusy(true); await updateTask(task.id, { completed: !task.completedAt }); setBusy(false); }}>{task.completedAt ? "✓" : ""}</button><div><strong>{task.title}</strong><p>{task.detail}</p><small>{task.category} · {task.priority} · {task.estimatedMinutes}m estimate{task.scheduledDate ? ` · ${task.scheduledDate}` : ""}{task.deadline && !task.completedAt && new Date(task.deadline) < new Date() ? " · OVERDUE" : ""}</small></div><div className={styles.taskActions}><button disabled={index === 0 || busy} onClick={() => void reorderTasks(week.id, move(week.tasks.map((item) => item.id), index, index - 1))}>↑</button><button disabled={index === week.tasks.length - 1 || busy} onClick={() => void reorderTasks(week.id, move(week.tasks.map((item) => item.id), index, index + 1))}>↓</button><button onClick={() => { setOpenWeek(week.id); setEditingTask(task); }}>Edit</button><button onClick={async () => { if (window.confirm(`Delete “${task.title}”?`)) await deleteTask(task.id); }}>Delete</button></div></article>) : <p className={styles.empty}>No tasks in this view.</p>}</div>
      <button className={styles.add} onClick={() => { setOpenWeek(week.id); setEditingTask(null); }}>+ Add task</button></section>; })}</div>
    {openWeek && <TaskDialog weekId={openWeek} task={editingTask} onClose={() => setOpenWeek(null)} onSave={async (input) => { setBusy(true); const ok = editingTask ? await updateTask(editingTask.id, input) : await createTask({ ...input, clientRequestId: crypto.randomUUID() }); setBusy(false); if (ok) setOpenWeek(null); }} busy={busy} />}
    {editingWeek && <WeekDialog week={editingWeek} busy={busy} onClose={() => setEditingWeek(null)} onSave={async (week) => { setBusy(true); const ok = await updateWeek(week); setBusy(false); if (ok) setEditingWeek(null); }} />}
  </div>;
}

function move(items: string[], from: number, to: number) { const next = [...items]; const [item] = next.splice(from, 1); next.splice(to, 0, item); return next; }

function TaskDialog({ weekId, task, onClose, onSave, busy }: { weekId: string; task: LearningTask | null; onClose: () => void; onSave: (input: Omit<Parameters<ReturnType<typeof useLearning>["createTask"]>[0], "clientRequestId">) => Promise<void>; busy: boolean }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await onSave({ weekId, title: String(data.get("title")), detail: String(data.get("detail")), scheduledDate: String(data.get("scheduledDate")) || null, estimatedMinutes: Number(data.get("estimatedMinutes")), actualMinutes: Number(data.get("actualMinutes")), priority: data.get("priority") as TaskPriority, category: data.get("category") as TaskCategory, deadline: data.get("deadline") ? new Date(String(data.get("deadline"))).toISOString() : null, position: task?.position ?? 999, completed: Boolean(task?.completedAt), notes: String(data.get("notes")) }); }
  return <div className={styles.backdrop}><form className={styles.dialog} onSubmit={submit}><h2>{task ? "Edit task" : "New task"}</h2><label>Title<input name="title" defaultValue={task?.title} required /></label><label>Description<textarea name="detail" defaultValue={task?.detail} /></label><div className={styles.two}><label>Scheduled date<input type="date" name="scheduledDate" defaultValue={task?.scheduledDate ?? ""} /></label><label>Deadline<input type="datetime-local" name="deadline" defaultValue={task?.deadline?.slice(0,16) ?? ""} /></label><label>Estimated minutes<input type="number" name="estimatedMinutes" min="0" defaultValue={task?.estimatedMinutes ?? 60} /></label><label>Actual minutes<input type="number" name="actualMinutes" min="0" defaultValue={task?.actualMinutes ?? 0} /></label><label>Priority<select name="priority" defaultValue={task?.priority ?? "medium"}><option>low</option><option>medium</option><option>high</option></select></label><label>Category<select name="category" defaultValue={task?.category ?? "course"}><option>course</option><option>practice</option><option>project</option><option>review</option></select></label></div><label>Notes<textarea name="notes" defaultValue={task?.notes} /></label><div className={styles.dialogActions}><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save task"}</button></div></form></div>;
}

function WeekDialog({ week, busy, onClose, onSave }: { week: PlanWeek; busy: boolean; onClose: () => void; onSave: (week: Omit<PlanWeek,"weekNumber"|"tasks">) => Promise<void> }) { async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await onSave({ id: week.id, title: String(data.get("title")), description: String(data.get("description")), outcome: String(data.get("outcome")), startsOn: String(data.get("startsOn")) || null, endsOn: String(data.get("endsOn")) || null, targetMinutes: Number(data.get("targetHours")) * 60, notes: String(data.get("notes")) }); } return <div className={styles.backdrop}><form className={styles.dialog} onSubmit={submit}><h2>Edit week {week.weekNumber}</h2><label>Title<input name="title" defaultValue={week.title} required /></label><label>Description<textarea name="description" defaultValue={week.description} /></label><label>Outcome<textarea name="outcome" defaultValue={week.outcome} /></label><div className={styles.two}><label>Start<input type="date" name="startsOn" defaultValue={week.startsOn ?? ""} /></label><label>End<input type="date" name="endsOn" defaultValue={week.endsOn ?? ""} /></label><label>Target hours<input type="number" name="targetHours" min="1" defaultValue={week.targetMinutes / 60} /></label></div><label>Notes<textarea name="notes" defaultValue={week.notes} /></label><div className={styles.dialogActions}><button type="button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? "Saving…" : "Save week"}</button></div></form></div>; }
